### ISSUE TITLE
go get failure

### ISSUE THREAD

**Issue by mewmew** [dhulihan/grump#4]
Hi,

I just tried to Go get grump, but ran into the following error. Just to let you know.

```
$ go get -v github.com/dhulihan/grump
go: downloading github.com/dhulihan/grump v0.0.0-20201015025354-2413accc6e5c
get "golang.org/x/sys": found meta tag vcs.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys?go-get=1
go get: github.com/dhulihan/grump@none updating to
	github.com/dhulihan/grump@v0.0.0-20201015025354-2413accc6e5c requires
	github.com/dhulihan/id3v2@v1.1.4-0.20200602041824-58c0f4d7150f: invalid version: unknown revision 58c0f4d7150f
```

Cheers,
Robin

**Edit:** oh, and just as a note, seek support for FLAC is soon to be added in Beep. https://github.com/faiface/beep/pull/111

**Comment by dhulihan** [comment]
Thanks for the catch @mewmew ! Forgot to run `go mod tidy` recently 😅 . Go ahead and try `go get -v github.com/dhulihan/grump` again. Let me know if that doesn't address this problem.

Also, that's exciting that flac seek support is coming soon! I'll keep an eye on that issue.

**Comment by mewmew** [comment]
> Thanks for the catch @mewmew ! Forgot to run go mod tidy recently sweat_smile . Go ahead and try go get -v github.com/dhulihan/grump again. Let me know if that doesn't address this problem.

Thanks, now it works!

> Also, that's exciting that flac seek support is coming soon! I'll keep an eye on that issue.

Definitely, this was the work of @cswank.
